### ISSUE TITLE
Problem with REMOTE_ADDRESS and REMOTE_PORT

### ISSUE THREAD

**Issue by hitman2599** [sebastianseilund/node-json-socket#19]
Hello there.

I have a question about your wonderfull library.

How i get remoteAddress and remotePort from an incoming JsonSocket? Basically i have a SERVER that recieves requests from the CLIENT. For example before using JSONSOCKET i could see

	root@sdb14 /home/node-js-test # node test-s.js
	SV.START [DRONE-SERVER] on XXX.XXX.XXX.XXX:5500 ...
	SV.SERVER.LISTENING[1]
	SV.SERVER.CONNECTION[1]
	SV.SOCKET.MESSAGE ping from [YYY.YYY.YYY.YYY:42942]
	SV.SOCKET.MESSAGE added new drone [YYY.YYY.YYY.YYY:42942]
	SV.SOCKET.MESSAGE ping from [YYY.YYY.YYY.YYY:42942]
	SV.SOCKET.MESSAGE ping from [YYY.YYY.YYY.YYY:42942]
	SV.SOCKET.MESSAGE ping from [YYY.YYY.YYY.YYY:42942]
	SV.SOCKET.MESSAGE ping from [YYY.YYY.YYY.YYY:42942]
	SV.SOCKET.MESSAGE ping from [YYY.YYY.YYY.YYY:42942]
	SV.SOCKET.MESSAGE ping from [YYY.YYY.YYY.YYY:42942]
	SV.SOCKET.MESSAGE ping from [YYY.YYY.YYY.YYY:42942]

now i see

	root@sdb14 /home/node-js-test # node test-s.js
	SV.START [DRONE-SERVER] on XXX.XXX.XXX.XXX:5500 ...
	SV.SERVER.LISTENING[1]
	SV.SERVER.CONNECTION[1]
	SV.SOCKET.MESSAGE ping from [undefined:undefined]
	SV.SOCKET.MESSAGE added new drone [YYY.YYY.YYY.YYY:42963]
	SV.SOCKET.MESSAGE ping from [undefined:undefined]
	SV.SOCKET.MESSAGE ping from [undefined:undefined]
	SV.SOCKET.MESSAGE ping from [undefined:undefined]
	SV.SOCKET.MESSAGE ping from [undefined:undefined]
	SV.SOCKET.MESSAGE ping from [undefined:undefined]
	SV.SOCKET.MESSAGE ping from [undefined:undefined]

after adding

	socket = new JsonSocket(socket);

and this is the line :

	else if(message.code == 101)
	{
		// PING
		if(debug >= 3) console.log("SV.SOCKET.MESSAGE ping from ["+socket.host+":"+socket.port+"]");
	}

Thanks.

**Comment by sebastianseilund** [comment]
`JsonSocket` simply wraps a normal [`net.Socket`](https://nodejs.org/dist/latest-v5.x/docs/api/net.html#net_class_net_socket). It currently doesn't offer _all_ the functionality that a normal socket does. So you should be able to get those properties from the original socket. Edited example from the README:

```
var net = require('net'),
    JsonSocket = require('json-socket');

var port = 9838;
var server = net.createServer();
server.listen(port);
server.on('connection', function(socket) { //This is a standard net.Socket
    var jsonSocket = new JsonSocket(socket); //Now we've decorated the net.Socket to be a JsonSocket
    jsonSocket.on('message', function(message) {
        var result = message.a + message.b;
        jsonSocket.sendEndMessage({result: result});
    });

  //LOOK HERE!!!
  console.log(socket.host)
  console.log(socket.port)
});
```

You _can_ also access the the original socket using `jsonSocket._socket`.
