### ISSUE TITLE
Faster

### ISSUE THREAD

**Issue by YouriT** [sebastianseilund/node-json-socket#22]
Hi @sebastianseilund,

I'm facing some speed issues, therefore I made some changes to enable json-socket to be faster but even thought it's not successful at all.

Are you able to have a speed above 15-20MBytes/s ? Because I'm not and that's really frustrating. If I just passe data along a socket without parsing it, I'm able to have around 600MBytes/s for the client and server being on the same machine.

**Comment by sebastianseilund** [comment]
I actually don't use this module anymore so I can't tell you anything about speed unfortunately. If speed is important to you I would look into other protocols, and probably something that doesn't rely on JSON. Protobufs fx. Good luck :)
