### ISSUE TITLE
sendMessage is not a function

### ISSUE THREAD

**Issue by steffenkj** [sebastianseilund/node-json-socket#24]
Hello,

I want to use json-socket in atom-editor. All works fine with javascript.
But I used to write the atom packages in coffee-script. So I have to translate the code in coffee.
I am able to connect to a server, but if i want to call the "sendMessage" method to send data I get the error "Uncaught TypeError: socket.sendMessage is not a function".

Best regards,

Steffen

**Comment by sebastianseilund** [comment]
Can you show some code to reproduce the issue? Thanks

**Comment by steffenkj** [comment]
Sure, here is the code

  @net = require('net')
  JsonSocket = require('json-socket')
  @port = 9471
  @server = @net.createServer()
  @server.listen @port
  @server.on 'connection', (socket) ->
     console.log "aktueller state " + @state
     #This is a standard net.Socket
     @socket = new JsonSocket(socket)
     console.log "Verbindung aufgebaut ++++++++++++"
     socket.sendMessage {"State":"2"}

**Comment by steffenkj** [comment]
Ok sry,  I got the mistake. I took the wrong socket variable.
Thank you for the fast response.
