### ISSUE TITLE
on('message') at server is not fired

### ISSUE THREAD

**Issue by muthurajbharathi** [sebastianseilund/node-json-socket#34]
jsonSocketServer = function(){
	var JsonSocket = require('json-socket');
	var JsonSocketserver = net.createServer();
	JsonSocketserver.listen(rBoxPort2);
	JsonSocketserver.on('connection', function(sock) {
	 //This is a standard net.Socket 
	 log("connected jsonsocketserver"); //this is getting printed but on message is not fired
    js = new JsonSocket(sock); //Now we've decorated the net.Socket to be a JsonSocket 
    js.on('message', function(message) {
    	try {
    		var obj = JSON.parse(message);
    		if (obj.hasOwnProperty('server-sw-check')) {
    			console.log('server-sw-check');
    			if (obj.hasOwnProperty('deviceArr')) {
    				checkDeviceSWversion(obj.deviceArr, function(data) {
    					log('data '+data);
    					js.sendMessage(JSON.stringify(data));
    				});
    			}
    		}
    	} catch (err) {
    		log("jason sock on msg err is : " + err);
    	}
    });

    js.on('end', function() {
        log(" jason sock end "); //after end close will happen
    });
    js.on('error', function(error) {
    	log('jason sock error :');
    	log(error);

    });
    js.on('close', function() {
    	log(" jason sock close ");
    });
    sock.on('drain', function() {
    	log('sock drain..');
        //i might have to handle something here....
    });
    sock.on('timeout', function() {
    	log('sock timeout : ');
        //i might have to handle something here....
    });

});
	JsonSocketserver.on('error', function(e) {
		if (e.code == 'EADDRINUSE') {
			log('CRITICAL ERROR : JsonSocketserver Address in use, retrying...');

		} else {
			log('CRITICAL ERROR : JsonSocketserver SERVER ERROR - ' + e.code);
		}
	});

	JsonSocketserver.on('end', function() {
		log('JsonSocketserver SERVER END');

	});

	JsonSocketserver.on('close', function() {
		log('JsonSocketserver SERVER CLOSE');

	});
}

setTimeout(jsonSocketServer,5000);

**Comment by sebastianseilund** [comment]
Thanks. Could you provide a more minimal code sample that displays the issue? There's a lot to parse through here and it's not obvious to me what your exact issue is.

**Comment by muthurajbharathi** [comment]
var JsonSocket = require('json-socket');
	var JsonSocketserver = net.createServer();
	JsonSocketserver.listen(rBoxPort2);
	JsonSocketserver.on('connection', function(sock) {
	 //This is a standard net.Socket 
	# **#  **log("connected jsonsocketserver");** this is getting printed in console log but on message is not fired**
    js = new JsonSocket(sock); //Now we've decorated the net.Socket to be a JsonSocket 
    js.on('message', function(message) {
    	try {
    		var obj = JSON.parse(message);
    		if (obj.hasOwnProperty('server-sw-check')) {
    			console.log('server-sw-check');
    			if (obj.hasOwnProperty('deviceArr')) {
    				checkDeviceSWversion(obj.deviceArr, function(data) {
    					log('data '+data);
    					js.sendMessage(JSON.stringify(data));
    				});
    			}
    		}
    	} catch (err) {
    		log("jason sock on msg err is : " + err);
    	}
    });
})
