### ISSUE TITLE
Length delimiter causing problems in receiving server

### ISSUE THREAD

**Issue by scotchbrite** [sebastianseilund/node-json-socket#9]
Hello:
I'm using JsonSocket and everything works as expected. The only problem I have is when reading the message sent in the server. I operate with a Python server and can't decode the json because of the length delimiter before the json string. Is there a way I can remove it or to take it into account on the python server?
Thanks for your help

**Comment by philiprhoades** [comment]
I have just been stymied by this problem as well (talking to a Java server) - it doesn't look like there is a solution? - I don't really want to have to change the API on the Java end . . 

Thanks,
Phil.

**Comment by sebastianseilund** [comment]
Your Java/Python servers would need to implement the same protocol that this library does.
